"""Create new tables

Revision ID: 3d40954d9ae0
Revises: 156f5d0542fb
Create Date: 2024-10-15 17:38:57.288914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d40954d9ae0'
down_revision: Union[str, None] = '156f5d0542fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company', sa.Column('email_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company', 'account', ['email_id'], ['id'])
    op.drop_column('company', 'email')
    op.drop_column('company', 'first_name')
    op.drop_column('company', 'last_name')
    op.drop_column('company', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'email_id')
    op.drop_table('secret')
    op.drop_table('user')
    # ### end Alembic commands ###
