"""Rename users tables

Revision ID: 3efa885c3fe9
Revises: 3d40954d9ae0
Create Date: 2024-10-15 17:55:35.784146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efa885c3fe9'
down_revision: Union[str, None] = '3d40954d9ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.drop_constraint('secret_user_id_fkey', 'secret', type_='foreignkey')
    op.create_foreign_key(None, 'secret', 'users', ['user_id'], ['id'])
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='user_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.drop_constraint(None, 'secret', type_='foreignkey')
    op.create_foreign_key('secret_user_id_fkey', 'secret', 'user', ['user_id'], ['id'])
    op.drop_table('users')
    # ### end Alembic commands ###
